# Script-mode helper invoked by embed_web_assets().
# Emits one `inline constexpr char kWebAsset_<name>[]` per file.

set(out "// Generated by GenerateAssets.cmake -- do not edit.\n#pragma once\n\n")

foreach(asset ${ASSETS})
  file(READ "${SOURCE_DIR}/${asset}" contents)

  get_filename_component(stem "${asset}" NAME_WE)
  get_filename_component(ext  "${asset}" EXT)
  string(REPLACE "." "" ext "${ext}")
  string(TOUPPER "${ext}" ext_upper)
  string(SUBSTRING "${ext_upper}" 0 1 ext_first)
  string(SUBSTRING "${ext}" 1 -1 ext_rest)
  set(symbol "kWebAsset_${stem}${ext_first}${ext_rest}")

  # A raw literal needs a delimiter the payload cannot contain.
  set(delim "WAP")
  if(contents MATCHES "\\)WAP\"")
    message(FATAL_ERROR "Asset ${asset} contains the raw-literal delimiter )WAP\"")
  endif()

  string(APPEND out "inline constexpr char ${symbol}[] = R\"${delim}(${contents})${delim}\";\n\n")
endforeach()

file(WRITE "${OUT_HEADER}" "${out}")
